# 项目相关配置
ruoyi:
  # 名称
  name: Platform
  # 版本
  version: 3.9.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/Platform/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: char

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
    domain-name: http://192.168.6.8
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    # 默认开发环境
#    active: druid
    active: dameng
    # 数据库类型
#    dbType: mysql
    dbType: dameng
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
#  helperDialect: mysql
  helperDialect: oracle
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 行为分析配置
experiment:
  base:
    stay-verify: false
    ranging-verify: true
    push-data: false
    output-shp: false
    output-shp-path: /Users/lixian/Cache/Platform/PlatformData/output
    delete-datetime: 2025-10-20 09:00:00
#    yard-name: yuzui
    yard-name: dongjiazhen
    location-card-type: other
    card-type: car

    joysuch:
#      building-name: 鱼嘴
#      building-id: 209885
      building-name: 董家镇
      building-id: 209983
#      username: 18911091136
#      password: 3W.163.com
#      base-url: https://api.joysuch.com:46000
      username: client
      password: JoySuch@client10
      base-url: http://61.50.136.180:46000
#      base-url: http://172.30.17.116/zqapi
      api:
        # 获取建筑列表
        build-list: ${experiment.base.joysuch.base-url}/api/v1/buildList
        # 获取设备列表
        cards: ${experiment.base.joysuch.base-url}/api/v4/device/blts
        # 获取标签列表
        beacons: ${experiment.base.joysuch.base-url}/api/v1/device/uwbBeacons
        # 获取标签历史轨迹
        points: ${experiment.base.joysuch.base-url}/api/v1/datacenter/historyPath
        # 订阅http和mq
        subscribe: ${experiment.base.joysuch.base-url}/api/v2/subscribe/http/subscribe
        # 取消订阅
        unsubscribe: ${experiment.base.joysuch.base-url}/api/v2/subscribe/http/unsubscribe
        # 获取标签和uwb扫描历史（测距）
        tag-scan-uwb-history: ${experiment.base.joysuch.base-url}/api/v1/device/tagScanUwbHistory
    sw-center:
      tenant-id: 10003
      #中心服务地址
      status: 1
#      center-ip: http://10.4.230.56:8000/sw-centralOpen-api
      center-ip: http://192.168.6.15/sw-centralOpen-api
      #RFID识别记录列表
      get-list: /api/station/getCompleteRfidList
    card-analysis:
      #车辆进场、出场推送
      vehicle-entry-exit: /api/cardAnalysis/vehicleEntryAndExit
      #车辆停放车位、车辆离开车位
      assignment-record: /api/cardAnalysis/assignmentRecord
      #实时轨迹
      vehicle-track: /api/cardAnalysis/mqVehicleTrackVo
      #UWB推送
      beacon-push: /api/cardAnalysis/beaconPush
      #车辆删除
      remove-vehicle: /api/cardAnalysis/removeAssignmentRecord
  file-path:
    yard-name: ${experiment.base.yard-name}
    base-path: /Users/lixian/Cache/Platform/PlatformData/shp
    yards:
      dongjiazhen:
        driving:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇库区/kuqu.shp
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇道路/zhugandao.shp
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇货运线J车/huoyunxianjc.shp
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇货运线作业台/huoyunxianzyt.shp
        parking:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇库区/kuqu.shp
        road:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇道路/zhugandao.shp
        parking2road:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇道路/zhugandao.shp
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇库区/kuqu.shp
        huoyunxin:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇货运线J车/huoyunxianjc.shp
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇货运线作业台/huoyunxianzyt.shp
        huoyunxinzyt:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇货运线作业台/huoyunxianzyt.shp
        huoyunxinjc:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇货运线J车/huoyunxianjc.shp
        banche:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇板车作业区/banchezuoyequ.shp
        zikuqu:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇库区/zikuqu.shp
        kuwei:
          - ${experiment.file-path.base-path}/dongjiazhen/董家镇库区/kuwei.shp
      minhang:
        driving:
          - ${experiment.file-path.base-path}/minhang/行车道路/xingcdaolu.shp
          - ${experiment.file-path.base-path}/minhang/20250624库区/kuqu.shp
          - ${experiment.file-path.base-path}/minhang/货运线/huoyunxin.shp
        parking:
          - ${experiment.file-path.base-path}/minhang/20250624库区/kuqu.shp
        road:
          - ${experiment.file-path.base-path}/minhang/行车道路/xingcdaolu.shp
        huoyunxin:
          - ${experiment.file-path.base-path}/minhang/货运线/huoyunxin.shp
      yuzui:
        driving:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴道路/daolu.shp
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴库区/kuqu.shp
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴货运线/huoyunxian.shp
        parking2road:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴道路/daolu.shp
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴库区/kuqu.shp
        parking:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴库区/kuqu.shp
        road:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴道路/daolu.shp
        huoyunxin:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴货运线/huoyunxian.shp
        huoyunxinzyt:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴货运线作业台/huoyunxianzyt.shp
        huoyunxinjc:
          - ${experiment.file-path.base-path}/yuzui/20250630鱼嘴货运线J车/huoyunxianjc.shp
        banche:
          - ${experiment.file-path.base-path}/yuzui/20250901鱼嘴板车作业区/banchezuoyequ.shp