-- 增加轨迹表索引
CREATE INDEX "ANALYSIS_PLATFORM"."IDX_TAK_BEHAVIOR_RECORD_DETAIL_TRACK_ID" ON "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORD_DETAIL"(TRACK_ID);
CREATE INDEX "ANALYSIS_PLATFORM"."IDX_TAK_BEHAVIOR_RECORD_DETAIL_IDX_TAK_BEHAVIOR_RECORD_DETAIL_CARD_ID_AND_TRACK_ID" ON "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORD_DETAIL"(CARD_ID,TRACK_ID);
