-- 添加感应距离字段
ALTER TABLE ANALYSIS_PLATFORM.TAK_BEACON_INFO ADD COLUMN DISTANCE DECIMAL(10,2) NULL;
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.DISTANCE IS '感应距离 m';

-- 添加楼层字段
ALTER TABLE "ANALYSIS_PLATFORM"."TAK_BEACON_INFO" ADD COLUMN "FLOOR" INT;
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_BEACON_INFO"."FLOOR" IS '楼层数 默认（不区分层数） 0 一层 1 二层 2';
-- 添加经纬度字段
ALTER TABLE "ANALYSIS_PLATFORM"."TAK_BEACON_INFO" ADD COLUMN "LONGITUDE" NUMBER(9,6);
ALTER TABLE "ANALYSIS_PLATFORM"."TAK_BEACON_INFO" ADD COLUMN "LATITUDE" NUMBER(9,6);
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_BEACON_INFO"."LONGITUDE" IS '经度';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_BEACON_INFO"."LATITUDE" IS '纬度';

-- 添加视觉匹配ID字段
ALTER TABLE "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORDS" ADD COLUMN "VISION_ID" BIGINT;
ALTER TABLE "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORDS" ADD COLUMN "VEHICLE_CODE" VARCHAR(50);
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORDS"."VISION_ID" IS '视觉匹配ID';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORDS"."VEHICLE_CODE" IS 'VIN码';

-- 添加推送状态字段
ALTER TABLE "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORDS" ADD COLUMN "PUSH_STATUS" INT DEFAULT (1) NULL;
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_BEHAVIOR_RECORDS"."PUSH_STATUS" IS '推送状态 0-已推送 1-未推送';