-- 数据匹配相关表结构SQL脚本
-- 适用于达梦数据库

ALTER TABLE "TAK_BEACON_INFO" ADD RFID_NAME VARCHAR(100);
COMMENT ON COLUMN "TAK_BEACON_INFO"."RFID_NAME" IS 'RFID名称';

-- 1. 为tak_behavior_records表添加匹配状态字段
ALTER TABLE "TAK_BEHAVIOR_RECORDS" ADD "MATCH_STATUS" INTEGER DEFAULT 0;
COMMENT ON COLUMN "TAK_BEHAVIOR_RECORDS"."MATCH_STATUS" IS '匹配状态：0-未匹配，1-匹配成功，2-作业数据多余（没有RFID匹配）';

ALTER TABLE "TAK_BEHAVIOR_RECORDS" ADD "MATCHED_RFID_ID" BIGINT;
COMMENT ON COLUMN "TAK_BEHAVIOR_RECORDS"."MATCHED_RFID_ID" IS '匹配的RFID记录ID';

ALTER TABLE "TAK_BEHAVIOR_RECORDS" ADD "MATCH_TIME" TIMESTAMP;
COMMENT ON COLUMN "TAK_BEHAVIOR_RECORDS"."MATCH_TIME" IS '匹配时间';

-- 2. 创建RFID识别记录表
CREATE TABLE "TAK_RFID_RECORD" (
    "ID" BIGINT PRIMARY KEY,
    "RECORD_CODE" VARCHAR(255),
    "VEHICLE_TIME" TIMESTAMP,
    "REGION_ID" VARCHAR(255),
    "DRIVER" VARCHAR(255),
    "OPERATE_STATION_ID" VARCHAR(255),
    "OPERATE_STATION" VARCHAR(255),
    "RFID" VARCHAR(255),
    "THIRD_ID" VARCHAR(255),
    "MATCH_STATUS" INTEGER DEFAULT 0,
    "MATCHED_JOB_ID" BIGINT,
    "MATCH_TIME" TIMESTAMP,
    "CREATE_TIME" TIMESTAMP,
    "UPDATE_TIME" TIMESTAMP
);

COMMENT ON TABLE "TAK_RFID_RECORD" IS 'RFID识别记录表';
COMMENT ON COLUMN "TAK_RFID_RECORD"."RECORD_CODE" IS 'RFID车辆认证码';
COMMENT ON COLUMN "TAK_RFID_RECORD"."VEHICLE_TIME" IS '识别时间';
COMMENT ON COLUMN "TAK_RFID_RECORD"."REGION_ID" IS 'RFID识别设备';
COMMENT ON COLUMN "TAK_RFID_RECORD"."DRIVER" IS '司机名称';
COMMENT ON COLUMN "TAK_RFID_RECORD"."OPERATE_STATION_ID" IS '操作站id';
COMMENT ON COLUMN "TAK_RFID_RECORD"."OPERATE_STATION" IS '操作站';
COMMENT ON COLUMN "TAK_RFID_RECORD"."RFID" IS 'RFID';
COMMENT ON COLUMN "TAK_RFID_RECORD"."THIRD_ID" IS '第三方主键ID';
COMMENT ON COLUMN "TAK_RFID_RECORD"."MATCH_STATUS" IS '匹配状态：0-未匹配，1-匹配成功，2-多余数据，3-重复数据';
COMMENT ON COLUMN "TAK_RFID_RECORD"."MATCHED_JOB_ID" IS '匹配的作业数据ID';
COMMENT ON COLUMN "TAK_RFID_RECORD"."MATCH_TIME" IS '匹配时间';
COMMENT ON COLUMN "TAK_RFID_RECORD"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "TAK_RFID_RECORD"."UPDATE_TIME" IS '更新时间';


-- 3. 创建索引
CREATE INDEX "IDX_RFID_VEHICLE_TIME" ON "TAK_RFID_RECORD"("VEHICLE_TIME");
CREATE INDEX "IDX_RFID_THIRD_ID" ON "TAK_RFID_RECORD"("THIRD_ID");
CREATE INDEX "IDX_RFID_MATCH_STATUS" ON "TAK_RFID_RECORD"("MATCH_STATUS");

CREATE INDEX "IDX_JOB_MATCH_STATUS" ON "TAK_BEHAVIOR_RECORDS"("MATCH_STATUS");
CREATE INDEX "IDX_JOB_MATCHED_RFID_ID" ON "TAK_BEHAVIOR_RECORDS"("MATCHED_RFID_ID");