-- 达梦8 数据库初始化脚本
-- 包含定位数据与状态数据的表结构定义

CREATE TABLE IF NOT EXISTS LOC_TRACK_RECORD (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    STATION_ID INT NOT NULL,
    CARD_ID VARCHAR(64) NOT NULL,
    IS_ALARM SMALLINT NOT NULL,
    IS_LOW_POWER SMALLINT NOT NULL,
    IS_STILL SMALLINT NOT NULL,
    SOURCE_CODE VARCHAR(64) NOT NULL,
    GPS_IS_VALID SMALLINT NOT NULL,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    SPEED DOUBLE,
    BEACONS_JSON CLOB,
    UWBS_JSON CLOB,
    RAW_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE LOC_TRACK_RECORD IS '定位数据记录主表';
COMMENT ON COLUMN LOC_TRACK_RECORD.STATION_ID IS '基站唯一标识（-1表示无效）';
COMMENT ON COLUMN LOC_TRACK_RECORD.CARD_ID IS '定位卡唯一标识';
COMMENT ON COLUMN LOC_TRACK_RECORD.IS_ALARM IS '是否按键报警（0 否，1 是）';
COMMENT ON COLUMN LOC_TRACK_RECORD.IS_LOW_POWER IS '定位卡是否低电（0 正常，1 低电）';
COMMENT ON COLUMN LOC_TRACK_RECORD.IS_STILL IS '定位卡是否静止（0 移动，1 静止）';
COMMENT ON COLUMN LOC_TRACK_RECORD.SOURCE_CODE IS '数据来源编码';
COMMENT ON COLUMN LOC_TRACK_RECORD.GPS_IS_VALID IS 'GPS是否有效（0 无效，1 有效）';
COMMENT ON COLUMN LOC_TRACK_RECORD.LATITUDE IS '纬度';
COMMENT ON COLUMN LOC_TRACK_RECORD.LONGITUDE IS '经度';
COMMENT ON COLUMN LOC_TRACK_RECORD.SPEED IS '速度（单位：m/s）';
COMMENT ON COLUMN LOC_TRACK_RECORD.BEACONS_JSON IS '信标数组 JSON 序列化';
COMMENT ON COLUMN LOC_TRACK_RECORD.UWBS_JSON IS 'UWB 基站数组 JSON 序列化';
COMMENT ON COLUMN LOC_TRACK_RECORD.RAW_PAYLOAD IS '原始数据 JSON';

CREATE INDEX IDX_LOC_TRACK_STATION ON LOC_TRACK_RECORD (STATION_ID);
CREATE INDEX IDX_LOC_TRACK_CARD ON LOC_TRACK_RECORD (CARD_ID);
CREATE INDEX IDX_LOC_TRACK_SOURCE ON LOC_TRACK_RECORD (SOURCE_CODE);



CREATE TABLE IF NOT EXISTS LOC_TRACK_BEACON (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    LOCATION_ID BIGINT NOT NULL,
    BEACON_ID INT,
    DISTANCE DOUBLE,
    IS_LOW_POWER SMALLINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOC_BEACON_RECORD FOREIGN KEY (LOCATION_ID)
        REFERENCES LOC_TRACK_RECORD (ID)
);

COMMENT ON TABLE LOC_TRACK_BEACON IS '定位数据关联的信标明细';

CREATE INDEX IDX_LOC_BEACON_LOCATION_ID ON LOC_TRACK_BEACON (LOCATION_ID);

CREATE TABLE IF NOT EXISTS LOC_TRACK_UWB (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    LOCATION_ID BIGINT NOT NULL,
    CARD_ID VARCHAR(64),
    UWB_ID VARCHAR(64),
    DISTANCE DOUBLE,
    ELECTRIC_QUANTITY SMALLINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOC_UWB_RECORD FOREIGN KEY (LOCATION_ID)
        REFERENCES LOC_TRACK_RECORD (ID)
);

COMMENT ON TABLE LOC_TRACK_UWB IS '定位数据关联的 UWB 基站明细';
COMMENT ON COLUMN LOC_TRACK_UWB.CARD_ID IS '定位卡唯一标识';

CREATE INDEX IDX_LOC_UWB_LOCATION_ID ON LOC_TRACK_UWB (LOCATION_ID);

CREATE TABLE IF NOT EXISTS LOC_STATUS_RECORD (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    STATION_ID INT NOT NULL,
    CARD_ID VARCHAR(64) NOT NULL,
    IS_ALARM SMALLINT NOT NULL,
    IS_LOW_POWER SMALLINT NOT NULL,
    IS_STILL SMALLINT NOT NULL,
    SOURCE_CODE VARCHAR(64) NOT NULL,
    CARD_POWER INT,
    CARD_FREQ INT,
    CARD_VERSION INT,
    RAW_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE LOC_STATUS_RECORD IS '定位卡状态数据记录';

CREATE INDEX IDX_LOC_STATUS_STATION ON LOC_STATUS_RECORD (STATION_ID);
CREATE INDEX IDX_LOC_STATUS_CARD ON LOC_STATUS_RECORD (CARD_ID);
CREATE INDEX IDX_LOC_STATUS_SOURCE ON LOC_STATUS_RECORD (SOURCE_CODE);