CREATE TABLE "ANALYSIS_PLATFORM"."TAK_CARD_INFO"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "CARD_ID" VARCHAR(64) NOT NULL,
    "YARD_ID" VARCHAR(64) NOT NULL,
    "YARD_NAME" VARCHAR(128) NOT NULL,
    "TYPE" VARCHAR(16) NOT NULL,
    "BIZ_TYPE" TINYINT NOT NULL,
    "ENABLED" TINYINT DEFAULT 1 NOT NULL,
    "CREATE_TIME" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    "UPDATE_TIME" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    CONSTRAINT "PK_TAK_CARD_INFO" NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "UK_TAK_CARD_INFO_CARD" UNIQUE("CARD_ID"),
    CONSTRAINT "CK_TAK_CARD_INFO_TYPE" CHECK("TYPE" IN ('ZQ', 'XRKC'))
    ,CONSTRAINT "CK_TAK_CARD_INFO_ENABLED" CHECK(ENABLED IN (0, 1))
    ,CONSTRAINT "CK_TAK_CARD_INFO_BIZ_TYPE" CHECK(BIZ_TYPE IN (0, 1))) STORAGE(ON "MAIN", CLUSTERBTR
);

COMMENT ON TABLE "ANALYSIS_PLATFORM"."TAK_CARD_INFO" IS '定位卡管理';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."ID" IS '主键ID';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."CARD_ID" IS '卡ID';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."YARD_ID" IS '货场ID';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."YARD_NAME" IS '货场名称';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."TYPE" IS '定位卡类型（ZQ真趣，XRKC新锐科创）';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."BIZ_TYPE" IS '业务类型（0板车 1火车）';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."ENABLED" IS '是否启用（0禁用 1启用）';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ANALYSIS_PLATFORM"."TAK_CARD_INFO"."UPDATE_TIME" IS '更新时间';