CREATE TABLE ANALYSIS_PLATFORM.TAK_BEACON_INFO (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(200) NOT NULL,
   "TYPE" VARCHAR(50) NOT NULL,
   BUILD_ID VARCHAR(200) NOT NULL,
   BEACON_ID VARCHAR(200) NULL,
   LOCATION VARCHAR(200) NULL,
   STATUS INT DEFAULT 0,
   CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
);


COMMENT ON TABLE ANALYSIS_PLATFORM.TAK_BEACON_INFO IS '信标信息表';

-- 添加列注释
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.ID IS 'ID';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.NAME IS '名称';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO."TYPE" IS '类型';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.BUILD_ID IS '建筑ID';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.BEACON_ID IS '信标ID';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.LOCATION IS '位置';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.STATUS IS '状态，0-正常，1-异常';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ANALYSIS_PLATFORM.TAK_BEACON_INFO.UPDATE_TIME IS '更新时间';
